[package]
authors = ['Kylin <https://github.com/kylin-network>']
edition = '2018'
homepage = 'https://kylin.network'
license = 'Apache 2.0'
name = 'development-runtime'
repository = 'https://github.com/kylin-network/kylin-collator/'
version = '2.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "1.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

log = { version = "0.4.14", default-features = false }

# Substrate Dependencies
## Substrate Primitive Dependencies
sp-api = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-block-builder = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-core = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-consensus-aura = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-inherents = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-io = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-offchain = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-runtime = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-session = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-std = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-transaction-pool = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
sp-version = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }

## Substrate FRAME Dependencies
frame-executive = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
frame-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false, optional = true }
frame-support = { git = 'https://github.com/paritytech/substrate', default-features = false, branch = 'master' }
frame-system = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
frame-system-benchmarking = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false, optional = true }
frame-system-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }

## Substrate Pallet Dependencies
pallet-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-assets = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-balances = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-collective = { git = "https://github.com/paritytech/substrate",  default-features = false , branch = "master" }
pallet-randomness-collective-flip = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-sudo = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-timestamp = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-transaction-payment = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-transaction-payment-rpc-runtime-api = { git = 'https://github.com/paritytech/substrate', branch = 'master', default-features = false }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
pallet-vesting = { git = "https://github.com/paritytech/substrate",  default-features = false , branch = "master" }
pallet-utility = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }


# Cumulus Dependencies
cumulus-pallet-aura-ext = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
cumulus-pallet-parachain-system = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
cumulus-pallet-dmp-queue  = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
cumulus-pallet-xcm = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
cumulus-pallet-xcmp-queue = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
cumulus-primitives-core = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
cumulus-primitives-timestamp = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
cumulus-primitives-utility = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
parachain-info = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }
parachains-common = { git = 'https://github.com/paritytech/cumulus', branch = 'master', default-features = false }

# Polkadot Dependencies
polkadot-parachain = { git = 'https://github.com/paritytech/polkadot', branch = 'master', default-features = false }
xcm = { git = 'https://github.com/paritytech/polkadot', branch = 'master', default-features = false }
xcm-builder = { git = 'https://github.com/paritytech/polkadot', branch = 'master', default-features = false }
xcm-executor = { git = 'https://github.com/paritytech/polkadot', branch = 'master', default-features = false }
pallet-xcm = { git = 'https://github.com/paritytech/polkadot', branch = 'master', default-features = false }


# Local Dependencies
kylin-oracle = { package = 'kylin-oracle', path = '../../pallets/kylin-oracle', default-features = false }
runtime-common = { path = "../common", default-features = false }
pallet-crowdloan-claim = { path = "../../pallets/crowdloan-claim", default-features = false }
pallet-crowdloan-reward = { path = "../../pallets/crowdloan-reward", default-features = false }
pallet-crowdloan-rewards = { path = "../../pallets/crowdloan-rewards", default-features = false }


[dev-dependencies]
hex-literal = "0.3.1"
hex = "0.4.3"

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "master" }

[features]
default = ['std']
runtime-benchmarks = [
	'sp-runtime/runtime-benchmarks',
	'frame-benchmarking',
	'frame-support/runtime-benchmarks',
	'frame-system-benchmarking',
	'frame-system/runtime-benchmarks',
	'pallet-balances/runtime-benchmarks',
	'pallet-timestamp/runtime-benchmarks',
	'kylin-oracle/runtime-benchmarks',
]
std = [
	'codec/std',
	'scale-info/std',
	'serde',
	'sp-api/std',
	'sp-std/std',
	'sp-io/std',
	'sp-core/std',
	'sp-consensus-aura/std',
	'sp-runtime/std',
	'sp-version/std',
	'sp-offchain/std',
	'sp-session/std',
	'sp-block-builder/std',
	'sp-transaction-pool/std',
	'sp-inherents/std',
	'frame-support/std',
	'frame-executive/std',
	'frame-system/std',
	'frame-system-rpc-runtime-api/std',
	"pallet-assets/std",
	"pallet-aura/std",
	'pallet-balances/std',
	'pallet-collective/std',
	'pallet-randomness-collective-flip/std',
	'pallet-timestamp/std',
	'pallet-sudo/std',
	'pallet-vesting/std',
	'pallet-transaction-payment/std',
	'pallet-utility/std',
	'parachain-info/std',
	'parachains-common/std',
	'cumulus-pallet-aura-ext/std',
	'cumulus-pallet-dmp-queue/std',
	'cumulus-pallet-parachain-system/std',
	'cumulus-primitives-core/std',
	'xcm/std',
	'xcm-builder/std',
	'xcm-executor/std',
	'cumulus-pallet-xcm/std',
	'cumulus-pallet-xcmp-queue/std',
	'cumulus-primitives-utility/std',
	'kylin-oracle/std',
	'pallet-crowdloan-claim/std',
	'pallet-crowdloan-reward/std',
	'pallet-crowdloan-rewards/std',
]

# A feature that should be enabled when the runtime should be build for on-chain
# deployment. This will disable stuff that shouldn't be part of the on-chain wasm
# to make it smaller like logging for example.
on-chain-release-build = [
	"sp-api/disable-logging",
]
